apiVersion: v1
kind: Service
metadata:
  name: hospitality-service
  labels:
    app: hospitality
spec:
  # Use NodePort for local/Minikube, LoadBalancer for cloud providers
  type: LoadBalancer
  selector:
    app: hospitality
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  sessionAffinity: None
  # For local development, uncomment nodePort and change type to NodePort:
  # nodePort: 30080
